fieldLayouts:
  dd1c9e27-aefa-43f3-adea-1117def8deb0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 53da4afb-d54c-48c3-8674-34e379962930
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cd29146b-6390-4a40-8e07-be8f136202e4
        userCondition: null
fs: abstracts
handle: abstracts
name: Abstracts
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
