color: null
fieldLayouts:
  3e1302a6-1855-4fcf-845d-9d224069cf18:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0bbf8946-303c-427e-8f8e-4f51742b9f6b
            handle: text
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3dc7c64-5e7c-4523-be85-03a8ca8c6d9f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 880170b6-2c83-4cf0-bbca-85f0607a7abd
        userCondition: null
handle: heading2
hasTitleField: false
icon: null
name: 'Heading 2'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
