color: null
fieldLayouts:
  ce497cda-7f19-4f7d-b9bd-623706e8ddd4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4410e0d7-1efd-473f-b6ac-b99f5b68b26d # Instructions - Instruction List - List
            handle: null
            includeInCards: false
            instructions: null
            label: List
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fdff0990-8172-45ae-af66-1bd56d042262
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fc9a6568-e908-4a67-abab-762d86ff6767
        userCondition: null
handle: instructionList
hasTitleField: false
icon: null
name: 'Instruction List'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
