color: null
fieldLayouts:
  f8f5eb72-0568-4b09-ba6e-1b839083b30a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: fa3b48ba-5e5b-4476-b793-17177f4abb16
            handle: null
            includeInCards: true
            instructions: null
            label: Quantity
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56ff9259-af45-40dd-a70b-e49797a37132
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5708c9ae-1357-4fc8-a376-a09d79128d68
            handle: null
            includeInCards: false
            instructions: null
            label: Unit
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08aafd09-f761-48ef-a323-6e9fbdd3f91e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 079b7b72-146c-4d30-88e3-156896f78cf3
            handle: null
            includeInCards: false
            instructions: null
            label: Ingredient
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 611fdd83-64a6-4d21-814b-e7ffa2358d9e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0cf58473-1cfd-473e-8e5e-312c9d73e1a2
            handle: null
            includeInCards: false
            instructions: null
            label: Preparation
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0eeae74-ad7d-4f5b-b528-81c868b7fe91
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3b8b5306-7da8-48b8-acc3-3b129dd00cf3
        userCondition: null
handle: listBlock
hasTitleField: false
icon: null
name: 'Ingredients - Ingredient List - List Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
