color: null
fieldLayouts:
  ed08868d-6fc9-4839-a3dc-17b05f4e3cb5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 07e297c6-5c12-4c1f-9720-59d1b760d9f2
            handle: null
            includeInCards: true
            instructions: null
            label: Description
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d076c75b-edb0-4464-9121-eeeb948fc374
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7f1b68ba-62a0-45a6-bb9a-ff3afb40334d
        userCondition: null
handle: theListBlock
hasTitleField: false
icon: null
name: 'Instructions - Instruction List - List Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
