field: 722f1a56-78fa-4d62-9345-3eed6ac377b9
fieldLayouts:
  7b0e335f-275f-43ca-9fea-43cb5b96c50f:
    tabs:
      -
        fields:
          ffaf3413-aa37-4373-87c3-a6429e660f3c:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  ffaf3413-aa37-4373-87c3-a6429e660f3c:
    contentColumnType: string
    fieldGroup: null
    handle: list
    instructions: ''
    name: List
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - fa3b48ba-5e5b-4476-b793-17177f4abb16
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 5708c9ae-1357-4fc8-a376-a09d79128d68
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 079b7b72-146c-4d30-88e3-156896f78cf3
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 0cf58473-1cfd-473e-8e5e-312c9d73e1a2
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_2_list}}'
      fieldLayout: table
      maxRows: ''
      minRows: ''
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: ingredientList
name: 'Ingredient List'
sortOrder: 2
