field: 722f1a56-78fa-4d62-9345-3eed6ac377b9 # Ingredients
fieldLayouts:
  7b0e335f-275f-43ca-9fea-43cb5b96c50f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ffaf3413-aa37-4373-87c3-a6429e660f3c # List
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e656382-7d3e-44fd-a1e6-cb1d9bdf82db
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 186072cb-e799-4c72-a788-40184a2af8c7
        userCondition: null
fields:
  ffaf3413-aa37-4373-87c3-a6429e660f3c: # List
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: list
    instructions: null
    name: List
    searchable: true
    settings:
      blockTypeFields: 0
      changedFieldIndicator: null
      columns:
        __assoc__:
          -
            - fa3b48ba-5e5b-4476-b793-17177f4abb16 # Quantity
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 5708c9ae-1357-4fc8-a376-a09d79128d68 # Unit
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 079b7b72-146c-4d30-88e3-156896f78cf3 # Ingredient
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 0cf58473-1cfd-473e-8e5e-312c9d73e1a2 # Preparation
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_2_list}}'
      fieldLayout: table
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: ingredientList
name: 'Ingredient List'
sortOrder: 2
