field: ee476a6d-cca9-43ef-9e7b-292856b4eda0 # Instructions (OLD)
fieldLayouts:
  ce497cda-7f19-4f7d-b9bd-623706e8ddd4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4410e0d7-1efd-473f-b6ac-b99f5b68b26d # List
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f42cb71-eed0-46d7-b486-fcbcd8ae3cdf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fc9a6568-e908-4a67-abab-762d86ff6767
        userCondition: null
fields:
  4410e0d7-1efd-473f-b6ac-b99f5b68b26d: # List
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: theList
    instructions: null
    name: List
    searchable: true
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 684790937
      columns:
        __assoc__:
          -
            - 07e297c6-5c12-4c1f-9720-59d1b760d9f2 # Description
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_5_thelist}}'
      fieldLayout: table
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
handle: instructionList
name: 'Instruction List'
sortOrder: 2
