field: ee476a6d-cca9-43ef-9e7b-292856b4eda0 # Instructions
fieldLayouts:
  ce497cda-7f19-4f7d-b9bd-623706e8ddd4:
    tabs:
      -
        elements:
          -
            fieldUid: 4410e0d7-1efd-473f-b6ac-b99f5b68b26d # List
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4410e0d7-1efd-473f-b6ac-b99f5b68b26d: # List
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: theList
    instructions: ''
    name: List
    searchable: true
    settings:
      contentTable: '{{%stc_thelist}}'
      fieldLayout: table
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: instructionList
name: 'Instruction List'
sortOrder: 2
