field: 4410e0d7-1efd-473f-b6ac-b99f5b68b26d # List
fieldLayouts:
  ed08868d-6fc9-4839-a3dc-17b05f4e3cb5:
    tabs:
      -
        elements:
          -
            fieldUid: 07e297c6-5c12-4c1f-9720-59d1b760d9f2 # Description
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  07e297c6-5c12-4c1f-9720-59d1b760d9f2: # Description
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      ckeConfig: 51a7b6e9-ddac-4ad7-98a0-50fa5e3d710a # Default
      columnType: text
      defaultTransform: ''
      enableSourceEditingForNonAdmins: true
      purifierConfig: ''
      purifyHtml: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
