field: 4410e0d7-1efd-473f-b6ac-b99f5b68b26d
fieldLayouts:
  ed08868d-6fc9-4839-a3dc-17b05f4e3cb5:
    tabs:
      -
        fields:
          07e297c6-5c12-4c1f-9720-59d1b760d9f2:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  07e297c6-5c12-4c1f-9720-59d1b760d9f2:
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
