changedFieldIndicator: null
field: ffaf3413-aa37-4373-87c3-a6429e660f3c # List
fieldLayouts:
  f8f5eb72-0568-4b09-ba6e-1b839083b30a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: fa3b48ba-5e5b-4476-b793-17177f4abb16 # Quantity
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d06670e-a6d9-4675-b2ec-771331b545ef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5708c9ae-1357-4fc8-a376-a09d79128d68 # Unit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f4e68c9-5fcc-40fe-a58e-8adec03a370a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 079b7b72-146c-4d30-88e3-156896f78cf3 # Ingredient
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 701c7bcc-717f-4bda-9e0c-022010059999
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0cf58473-1cfd-473e-8e5e-312c9d73e1a2 # Preparation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d554c332-1aa9-44a0-a2ed-91a0722d3170
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3b8b5306-7da8-48b8-acc3-3b129dd00cf3
        userCondition: null
fields:
  0cf58473-1cfd-473e-8e5e-312c9d73e1a2: # Preparation
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: preparation
    instructions: null
    name: Preparation
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  079b7b72-146c-4d30-88e3-156896f78cf3: # Ingredient
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: ingredient
    instructions: null
    name: Ingredient
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5708c9ae-1357-4fc8-a376-a09d79128d68: # Unit
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: unit
    instructions: null
    name: Unit
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - Select...
            -
              - value
              - ''
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Grams
            -
              - value
              - gram
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Ounces
            -
              - value
              - ounce
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Pounds
            -
              - value
              - pound
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Teaspoons
            -
              - value
              - tsp
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tablespoons
            -
              - value
              - tbsp
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Cups
            -
              - value
              - cup
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  fa3b48ba-5e5b-4476-b793-17177f4abb16: # Quantity
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: quantity
    instructions: null
    name: Quantity
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
