field: ffaf3413-aa37-4373-87c3-a6429e660f3c # List
fieldLayouts:
  f8f5eb72-0568-4b09-ba6e-1b839083b30a:
    tabs:
      -
        elements:
          -
            fieldUid: fa3b48ba-5e5b-4476-b793-17177f4abb16 # Quantity
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5708c9ae-1357-4fc8-a376-a09d79128d68 # Unit
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 079b7b72-146c-4d30-88e3-156896f78cf3 # Ingredient
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0cf58473-1cfd-473e-8e5e-312c9d73e1a2 # Preparation
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0cf58473-1cfd-473e-8e5e-312c9d73e1a2: # Preparation
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: preparation
    instructions: ''
    name: Preparation
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  079b7b72-146c-4d30-88e3-156896f78cf3: # Ingredient
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: ingredient
    instructions: ''
    name: Ingredient
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5708c9ae-1357-4fc8-a376-a09d79128d68: # Unit
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: unit
    instructions: ''
    name: Unit
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Select...
            -
              - value
              - ''
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Grams
            -
              - value
              - gram
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Ounces
            -
              - value
              - ounce
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Pounds
            -
              - value
              - pound
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Teaspoons
            -
              - value
              - tsp
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tablespoons
            -
              - value
              - tbsp
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Cups
            -
              - value
              - cup
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  fa3b48ba-5e5b-4476-b793-17177f4abb16: # Quantity
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: quantity
    instructions: ''
    name: Quantity
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
