columnSuffix: null
contentColumnType: string
fieldGroup: 458c394f-cc78-4e33-a441-53fe1259f9fe # Common
handle: dietCats
instructions: null
name: 'Dietary Restrictions'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: true
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  source: 'group:c5196221-f005-4c3a-bc04-70d1e28bc99a' # Dietary Restrictions
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
