columnSuffix: null
contentColumnType: string
fieldGroup: 458c394f-cc78-4e33-a441-53fe1259f9fe # Common
handle: mealCats
instructions: ''
name: 'Meal Type'
searchable: true
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: 'group:17d65186-6f71-4a63-98a0-616a23f4aadf' # Meal Type
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
