columnSuffix: null
contentColumnType: string(255)
handle: recipeSourceUrl
instructions: null
name: 'Source URL'
searchable: true
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
