columnSuffix: null
contentColumnType: text
handle: recipeNotes
instructions: ''
name: Notes
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 5608699a-2abf-4fde-9835-23363d52bf75 # Simple
  columnType: text
  defaultTransform: ''
  enableSourceEditingForNonAdmins: true
  purifierConfig: ''
  purifyHtml: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
