columnSuffix: null
contentColumnType: text
fieldGroup: d5cb584b-a191-439e-a50e-d608943c5bba # Recipes
handle: recipeNotes
instructions: ''
name: Notes
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 7c390ba0-0f07-455d-902c-62b08143455b # Simple 2
  columnType: text
  defaultTransform: ''
  enableSourceEditingForNonAdmins: true
  purifierConfig: ''
  purifyHtml: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
