columnSuffix: null
contentColumnType: string
handle: recipeIngredients
instructions: null
name: 'Ingredients (OLD)'
searchable: true
settings:
  entryTypes:
    -
      uid: 93935eb3-7f6c-4bec-a150-2960739b1761
    -
      uid: fffa8870-5ac8-4278-abcf-b2341f6c359b
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
