columnSuffix: null
contentColumnType: string(255)
handle: recipeSourceUrl
instructions: ''
name: 'Source URL'
searchable: true
settings:
  maxLength: '255'
  placeholder: ''
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
