columnSuffix: null
contentColumnType: text
fieldGroup: d5cb584b-a191-439e-a50e-d608943c5bba # Recipes
handle: recipeNotes
instructions: null
name: Notes
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 5608699a-2abf-4fde-9835-23363d52bf75 # Simple
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: true
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
