columnSuffix: null
contentColumnType: text
fieldGroup: d5cb584b-a191-439e-a50e-d608943c5bba # Recipes
handle: recipeNotes
instructions: ''
name: Notes
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 528ecf5e-975b-4435-8ed7-c64dd1325ad5 # Simple
  columnType: text
  defaultTransform: ''
  enableSourceEditingForNonAdmins: true
  purifierConfig: ''
  purifyHtml: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
