columnSuffix: null
contentColumnType: integer(10)
fieldGroup: d5cb584b-a191-439e-a50e-d608943c5bba # Recipes
handle: recipeServes
instructions: ''
name: Serves
searchable: true
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: '2'
  suffix: People
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
