dateModified: 1722546109
email:
  fromEmail: $SYSTEM_EMAIL
  fromName: 'Dinner at 8'
  replyToEmail: null
  template: null
  transportSettings:
    command: ''
  transportType: craft\mail\transportadapters\Sendmail
fs:
  abstracts:
    hasUrls: true
    name: Abstracts
    settings:
      addSubfolderToRootUrl: '1'
      autoFocalPoint: ''
      bucket: content.dinnerat8.kristengrote.com
      bucketSelectionMode: choose
      cfDistributionId: ''
      cfPrefix: ''
      expires: '30 days'
      keyId: $S3_ACCESS_KEY_ID
      makeUploadsPublic: '1'
      region: us-west-2
      secret: $S3_SECRET_ACCESS_KEY
      subfolder: abstracts
    type: craft\awss3\Fs
    url: 'https://s3.us-west-2.amazonaws.com/content.dinnerat8.kristengrote.com'
meta:
  __names__:
    1f90e8f0-5924-44d5-a5df-5209b41e492e: 'Instructions - Instruction List - List Block' # Instructions - Instruction List - List Block
    02cd0f87-4960-4c1c-a0ab-e31ebb79ec7b: Holiday # Holiday
    2cd4e019-1eaa-4e94-8b43-3392c0fdd322: Season # Season
    3fe9a343-7987-489e-8daa-7d7a23d2c85b: Recipes # Recipes
    5c82a1d8-e0a1-4299-9c96-e0c780383c4b: 'Public Schema' # Public Schema
    5ed3311c-702e-42e8-b0c3-c0e89357c5c9: 'Source Name' # Source Name
    7a07bf60-7f14-4996-b14f-9e5d7660db57: Makes # Makes
    9fb4f6ff-06bf-48f1-925e-3fdd71f3a713: Recipes # Recipes
    17d65186-6f71-4a63-98a0-616a23f4aadf: 'Meal Type' # Meal Type
    24be567a-7441-4eaf-b03c-9cd3f0046c58: 'Protein Type' # Protein Type
    30f80e02-aeae-448c-a172-c2a5b7671d2a: Notes # Notes
    66b86147-ec5f-495f-9729-1f9614c6ff6e: 'Source URL' # Source URL
    68fd680f-8684-4ede-b14b-9d634ca2912b: Default # Default
    722f1a56-78fa-4d62-9345-3eed6ac377b9: Ingredients # Ingredients
    3607ce79-fa08-4429-9bdf-362a211f0419: Serves # Serves
    4410e0d7-1efd-473f-b6ac-b99f5b68b26d: 'Instructions - Instruction List - List' # Instructions - Instruction List - List
    419135b9-5aea-48a3-8ba2-9c58221d424f: 'Meal Type' # Meal Type
    5608699a-2abf-4fde-9835-23363d52bf75: Simple # Simple
    7955371b-f46b-47a4-99f0-8c79e0ed88d2: Season # Season
    19752013-301c-4d1e-835a-85c15af48ac0: 'Dinner at 8' # Dinner at 8
    b4f23826-1085-4863-b1b2-9c286abe46f1: 'Dietary Restrictions' # Dietary Restrictions
    c5196221-f005-4c3a-bc04-70d1e28bc99a: 'Dietary Restrictions' # Dietary Restrictions
    ca0c05de-cddd-4a8f-9578-ab1c34092593: 'Protein Type' # Protein Type
    cb756273-ee04-4796-b4b9-cb450fc5a38a: Abstracts # Abstracts
    cd412959-aebd-403a-b455-0c9fbcedf68a: Holiday # Holiday
    d99fda2a-6512-4e74-9162-14968199b4eb: Image # Image
    ec35b5a9-056f-4fd1-add4-f4faa4576b17: 'Dinner at 8' # Dinner at 8
    ee476a6d-cca9-43ef-9e7b-292856b4eda0: Instructions # Instructions
    f7646939-482b-4287-8489-69001f4719ef: 'Ingredients - Ingredient List - List Block' # Ingredients - Ingredient List - List Block
    ffaf3413-aa37-4373-87c3-a6429e660f3c: 'Ingredients - Ingredient List - List' # Ingredients - Ingredient List - List
plugins:
  assetrev:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '2.0'
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  element-api:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 4.0.0
system:
  edition: solo
  live: true
  name: 'Dinner at 8'
  schemaVersion: 5.0.0.21
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
