handle: diet
name: 'Dietary Restrictions'
siteSettings:
  19752013-301c-4d1e-835a-85c15af48ac0:
    hasUrls: true
    template: ''
    uriFormat: 'dietary-restrictions/{slug}'
structure:
  maxLevels: null
  uid: dfc40794-e924-4076-b280-b5f35ff2f87c
