defaultPlacement: end
fieldLayouts:
  e3f4ddf2-fe0f-4935-9891-77639c8136d4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: a7e3392d-27bf-4425-bf35-6c5ac461338b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d58978c1-7593-4894-b51e-3f7eacbbc1de
        userCondition: null
handle: diet
name: 'Dietary Restrictions'
siteSettings:
  19752013-301c-4d1e-835a-85c15af48ac0: # Dinner at 8
    hasUrls: true
    template: null
    uriFormat: 'dietary-restrictions/{slug}'
structure:
  maxLevels: null
  uid: dfc40794-e924-4076-b280-b5f35ff2f87c
