defaultPlacement: end
fieldLayouts:
  1826f366-ebaa-4afa-8a03-6ea2b9a8197d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: holiday
name: Holiday
siteSettings:
  19752013-301c-4d1e-835a-85c15af48ac0: # Dinner at 8
    hasUrls: true
    template: null
    uriFormat: 'holiday/{slug}'
structure:
  maxLevels: null
  uid: 0d7d47ba-094b-41e8-8a00-68e8efa7d067
