defaultPlacement: end
fieldLayouts:
  09d6d4c9-5644-4f84-bd94-20ea2db8dd7c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: d64bd3c5-884d-49b8-a7c2-efbaf3182a0f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 96c45770-7d10-43a2-80d9-27f5a111ae01
        userCondition: null
handle: meal
name: 'Meal Type'
siteSettings:
  19752013-301c-4d1e-835a-85c15af48ac0: # Dinner at 8
    hasUrls: true
    template: null
    uriFormat: 'meal-type/{slug}'
structure:
  maxLevels: null
  uid: a6fadff6-7633-4cf4-9f89-78dc638bd28a
