defaultPlacement: end
fieldLayouts:
  7f74d2ca-6ba0-4743-bfd8-b9352b9b821a:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: protein
name: 'Protein Type'
siteSettings:
  19752013-301c-4d1e-835a-85c15af48ac0: # Dinner at 8
    hasUrls: true
    template: null
    uriFormat: 'protein-type/{slug}'
structure:
  maxLevels: null
  uid: 36657d8f-d20f-4519-8d4e-a955ae9713d4
