defaultPlacement: end
fieldLayouts:
  fa9197d6-1cbc-4da4-a7b1-535aa409060c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: season
name: Season
siteSettings:
  19752013-301c-4d1e-835a-85c15af48ac0: # Dinner at 8
    hasUrls: true
    template: null
    uriFormat: 'season/{slug}'
structure:
  maxLevels: null
  uid: 51f3a765-7aef-4d47-baf7-e7fdf920697f
